/**
 * Native-messaging host installer (Chrome-family).
 *
 * On desktop startup we register the `com.workx.desktop` native-messaging host
 * so the extension can `chrome.runtime.connectNative(...)` with zero pairing.
 * This writes three things:
 *
 *   1. a **wrapper** executable that runs the bundled Node against `relay.mjs`
 *      with the app-server URL + token-file path in its env,
 *   2. a **token file** (0600) the relay reads for the relay→app-server hop,
 *   3. the **host manifest** JSON into each installed Chrome-family browser's
 *      `NativeMessagingHosts/` dir, naming the wrapper as `path` and pinning the
 *      extension id in `allowed_origins`.
 *
 * Firefox uses a different manifest schema/location and is intentionally out of
 * scope for this cut (Chrome/Chromium/Edge/Brave share one format).
 *
 * @module desktop-runtime/browser-bridge/native-host/installNativeHost
 */

import { chmod, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const NATIVE_HOST_NAME = 'com.workx.desktop';

/**
 * Pinned Chrome extension id, derived from the public `key` in manifest.json.
 * Chrome computes the id as SHA-256(DER SPKI)[:16] mapped 0-9a-f → a-p; pinning
 * the manifest key makes this id stable across every unpacked/CRX load, so the
 * host manifest's `allowed_origins` can authorize it ahead of time.
 */
export const WORKX_EXTENSION_ID = 'fdopfohnbeknmiklninbkkdknpenihki';

export interface NativeHostManifest {
  name: string;
  description: string;
  path: string;
  type: 'stdio';
  allowed_origins: string[];
}

/** The manifest Chrome reads to locate + authorize the host. */
export function buildHostManifest(wrapperPath: string, extensionId: string): NativeHostManifest {
  return {
    name: NATIVE_HOST_NAME,
    description: 'WorkX desktop browser bridge',
    path: wrapperPath,
    type: 'stdio',
    // Trailing slash is required by Chrome for extension origins.
    allowed_origins: [`chrome-extension://${extensionId}/`],
  };
}

/**
 * The per-browser `NativeMessagingHosts` directories for the current OS. We
 * write to all of them unconditionally — a dir for an uninstalled browser is
 * simply never read, which is cheaper than probing for each browser.
 */
export function chromiumHostDirs(platform: NodeJS.Platform, home: string): string[] {
  if (platform === 'darwin') {
    const base = path.join(home, 'Library', 'Application Support');
    return [
      path.join(base, 'Google', 'Chrome', 'NativeMessagingHosts'),
      path.join(base, 'Chromium', 'NativeMessagingHosts'),
      path.join(base, 'Microsoft Edge', 'NativeMessagingHosts'),
      path.join(base, 'BraveSoftware', 'Brave-Browser', 'NativeMessagingHosts'),
    ];
  }
  // Linux (Windows uses registry keys, not dirs — handled separately later).
  const cfg = path.join(home, '.config');
  return [
    path.join(cfg, 'google-chrome', 'NativeMessagingHosts'),
    path.join(cfg, 'chromium', 'NativeMessagingHosts'),
    path.join(cfg, 'microsoft-edge', 'NativeMessagingHosts'),
    path.join(cfg, 'BraveSoftware', 'Brave-Browser', 'NativeMessagingHosts'),
  ];
}

/** POSIX wrapper: run the bundled node against relay.mjs with bridge env set. */
function wrapperScript(nodePath: string, relayPath: string, appServerUrl: string, tokenFile: string): string {
  return [
    '#!/bin/sh',
    '# Auto-generated by WorkX. Runs the native-messaging relay.',
    `export WORKX_APP_SERVER_URL='${appServerUrl}'`,
    `export WORKX_BRIDGE_TOKEN_FILE='${tokenFile}'`,
    `exec '${nodePath}' '${relayPath}' "$@"`,
    '',
  ].join('\n');
}

export interface InstallOptions {
  /** Path to the bundled Node binary (sidecar node). */
  nodePath: string;
  /** Path to relay.mjs (bundled alongside the sidecar). */
  relayPath: string;
  /** app-server WS URL, e.g. ws://127.0.0.1:18101. */
  appServerUrl: string;
  /** Current capability token the relay must present. */
  token: string;
  /** Pinned extension id for allowed_origins. */
  extensionId: string;
  /** Writable per-user data dir for the wrapper + token file (e.g. ~/.config/workx). */
  dataDir: string;
  home: string;
  platform: NodeJS.Platform;
}

/**
 * Write the wrapper + token + per-browser manifests. Best-effort per directory:
 * a browser dir that can't be created/written is logged and skipped so one bad
 * profile never blocks the others.
 */
export async function installNativeHost(opts: InstallOptions): Promise<{ wrapperPath: string; written: string[] }> {
  const wrapperPath = path.join(opts.dataDir, 'workx-native-host.sh');
  const tokenFile = path.join(opts.dataDir, 'bridge-native-token');

  await mkdir(opts.dataDir, { recursive: true });
  await writeFile(tokenFile, opts.token, { mode: 0o600 });
  await writeFile(wrapperPath, wrapperScript(opts.nodePath, opts.relayPath, opts.appServerUrl, tokenFile), {
    mode: 0o700,
  });

  const manifest = JSON.stringify(buildHostManifest(wrapperPath, opts.extensionId), null, 2);
  const written: string[] = [];
  for (const dir of chromiumHostDirs(opts.platform, opts.home)) {
    const target = path.join(dir, `${NATIVE_HOST_NAME}.json`);
    try {
      await mkdir(dir, { recursive: true });
      await writeFile(target, manifest);
      written.push(target);
    } catch (err) {
      console.warn(`[native-host] could not write ${target}:`, err instanceof Error ? err.message : err);
    }
  }
  console.log(`[native-host] installed ${NATIVE_HOST_NAME} for ${written.length} browser dir(s)`);
  return { wrapperPath, written };
}
