/**
 * Schedule Event Type Definitions
 *
 * New data model separating schedule management (when to run)
 * from job execution (how to run).
 *
 * ScheduleEvent = the "what" and "when" (1 record per recurring series)
 * ExecutionRecord = the "result" (1 record per actual run)
 * ScheduleEventException = per-instance overrides
 * CalendarInstance = expanded virtual instance for UI
 */

import type { JobResultRecord } from './Scheduler';

// ============================================================================
// Execution Status
// ============================================================================

export type ExecutionStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

// ============================================================================
// Schedule Event
// ============================================================================

/**
 * A schedule event represents a single or recurring task.
 * For recurring events, one ScheduleEvent + RRULE expands to many virtual instances.
 */
export interface ScheduleEvent {
  /** UUID primary key */
  id: string;

  /** User's task/prompt */
  input: string;

  /** First occurrence time (Unix ms) */
  scheduledTime: number;

  /** RFC 5545 RRULE string, null = one-shot event */
  rrule: string | null;

  /** Whether this event is active (can be paused) */
  enabled: boolean;

  /** Deleted instance times (EXDATE in iCal terms) */
  exdates: number[];

  /** Unix timestamp (ms) when event was created */
  createdAt: number;

  /** Unix timestamp (ms) when event was last updated */
  updatedAt: number;
}

// ============================================================================
// Execution Record
// ============================================================================

/**
 * An execution record tracks a single run of a schedule event instance.
 * One per actual execution (not per virtual occurrence).
 */
export interface ExecutionRecord {
  /** UUID primary key */
  id: string;

  /** FK to ScheduleEvent */
  scheduleEventId: string;

  /** Which occurrence this execution is for (Unix ms) */
  instanceTime: number;

  /** The input/prompt text for this execution (preserved for queued jobs) */
  input: string;

  /** AgentRegistry session ID */
  sessionId: string | null;

  /** Execution lifecycle status */
  status: ExecutionStatus;

  /** Execution result (set on completion) */
  result: JobResultRecord | null;

  /** Error message if execution failed */
  error: string | null;

  /** When execution started (Unix ms) */
  startedAt: number | null;

  /** When execution completed (Unix ms) */
  completedAt: number | null;
}

// ============================================================================
// Schedule Event Exception
// ============================================================================

/**
 * Per-instance override for a recurring schedule event.
 * Allows editing a single instance without affecting the series.
 */
export interface ScheduleEventException {
  /** FK to ScheduleEvent */
  scheduleEventId: string;

  /** Original time of the instance this overrides (Unix ms) */
  instanceTime: number;

  /** Override the input/prompt for this instance */
  overrideInput?: string;

  /** Override the scheduled time for this instance */
  overrideTime?: number;
}

// ============================================================================
// Calendar Instance (Virtual)
// ============================================================================

/**
 * Calendar instance status for UI display.
 * Combines schedule state with execution state.
 */
export type CalendarInstanceStatus =
  | 'upcoming'   // Future, no execution yet
  | 'running'    // Currently executing
  | 'completed'  // Execution succeeded
  | 'failed'     // Execution failed
  | 'cancelled'  // Execution was cancelled
  | 'missed';    // Past time, no execution

/**
 * Expanded virtual instance for calendar UI display.
 * These are generated by expanding RRULE over a date range
 * and merging with actual ExecutionRecords.
 */
export interface CalendarInstance {
  /** FK to ScheduleEvent */
  scheduleEventId: string;

  /** The time of this instance (Unix ms) */
  instanceTime: number;

  /** The input/prompt (may be overridden by exception) */
  input: string;

  /** Combined status for display */
  status: CalendarInstanceStatus;

  /** FK to ExecutionRecord if one exists */
  executionId?: string;

  /** True if no ExecutionRecord exists yet (future/virtual) */
  isVirtual: boolean;

  /** Human-readable recurrence description */
  rruleDescription?: string;

  /** Whether this event is enabled */
  enabled: boolean;
}

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Create a new ScheduleEvent
 */
export function createScheduleEvent(
  id: string,
  input: string,
  scheduledTime: number,
  rrule: string | null = null
): ScheduleEvent {
  const now = Date.now();
  return {
    id,
    input,
    scheduledTime,
    rrule,
    enabled: true,
    exdates: [],
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Create a new ExecutionRecord
 */
export function createExecutionRecord(
  id: string,
  scheduleEventId: string,
  instanceTime: number,
  input: string = ''
): ExecutionRecord {
  return {
    id,
    scheduleEventId,
    instanceTime,
    input,
    sessionId: null,
    status: 'pending',
    result: null,
    error: null,
    startedAt: null,
    completedAt: null,
  };
}

// ============================================================================
// Type Guards
// ============================================================================

const VALID_EXECUTION_STATUSES: ExecutionStatus[] = [
  'pending', 'running', 'completed', 'failed', 'cancelled',
];

export function isExecutionStatus(value: string): value is ExecutionStatus {
  return VALID_EXECUTION_STATUSES.includes(value as ExecutionStatus);
}

export function isScheduleEvent(obj: unknown): obj is ScheduleEvent {
  if (!obj || typeof obj !== 'object') return false;
  const e = obj as Record<string, unknown>;
  return (
    typeof e.id === 'string' &&
    typeof e.input === 'string' &&
    typeof e.scheduledTime === 'number' &&
    (e.rrule === null || typeof e.rrule === 'string') &&
    typeof e.enabled === 'boolean' &&
    Array.isArray(e.exdates) &&
    typeof e.createdAt === 'number' &&
    typeof e.updatedAt === 'number'
  );
}

export function isExecutionRecord(obj: unknown): obj is ExecutionRecord {
  if (!obj || typeof obj !== 'object') return false;
  const r = obj as Record<string, unknown>;
  return (
    typeof r.id === 'string' &&
    typeof r.scheduleEventId === 'string' &&
    typeof r.instanceTime === 'number' &&
    typeof r.status === 'string' &&
    isExecutionStatus(r.status)
  );
}
