/**
 * Settings Search Registry
 *
 * Centralized registry of all searchable settings items for the settings search feature.
 * Each entry maps to a specific setting across the 6 settings sections.
 */

export interface SettingsSearchItem {
  id: string;
  labelKey: string;
  descriptionKey: string;
  section: SettingsSection;
  sectionLabelKey: string;
  keywords: string[];
  navigationTarget: NavigationView;
  elementId: string;
  conditional?: ConditionalRule;
}

export enum SettingsSection {
  MODEL_CONFIG = 'model-config',
  GENERAL = 'general',
  KEYBOARD_SHORTCUTS = 'keyboard-shortcuts',
  MEMORY = 'memory',
  STORAGE = 'storage',
  TOOLS = 'tools',
  DATA_SOURCES = 'data-sources',
  COMPONENTS = 'components',
  MCP_SERVERS = 'mcp-servers',
  APPROVAL = 'approval',
  EXTENSION = 'extension',
}

export interface ConditionalRule {
  type: 'platform' | 'feature';
  value: string;
}

export type NavigationView =
  | 'menu'
  | 'model-config'
  | 'advanced-model-config'
  | 'general'
  | 'keyboard-shortcuts'
  | 'memory'
  | 'storage'
  | 'tools'
  | 'data-sources'
  | 'components'
  | 'mcp-servers'
  | 'approval'
  | 'extension';

export const settingsRegistry: SettingsSearchItem[] = [
  {
    id: 'components.manage',
    labelKey: 'Components',
    descriptionKey: 'Install optional local tools and runtimes privately for WorkX.',
    section: SettingsSection.COMPONENTS,
    sectionLabelKey: 'Components',
    keywords: ['component', 'runtime', 'duckdb', 'install', 'local tool', 'python'],
    navigationTarget: 'components',
    elementId: 'components-title',
    conditional: { type: 'platform', value: 'desktop' },
  },
  {
    id: 'dataSources.manage',
    labelKey: 'Data Sources',
    descriptionKey: 'Connect and manage read-only PostgreSQL and MySQL databases.',
    section: SettingsSection.DATA_SOURCES,
    sectionLabelKey: 'Data Sources',
    keywords: ['database', 'postgres', 'postgresql', 'mysql', 'sql', 'analysis', 'context'],
    navigationTarget: 'data-sources',
    elementId: 'data-sources-title',
    conditional: { type: 'platform', value: 'desktop' },
  },
  // ── Model Config ──────────────────────────────────────────────────────
  {
    id: 'model.selection',
    labelKey: 'Choose AI Model',
    descriptionKey: 'Select the AI model to use for conversations.',
    section: SettingsSection.MODEL_CONFIG,
    sectionLabelKey: 'Model Config',
    keywords: ['model', 'ai', 'llm', 'provider', 'switch', 'change'],
    navigationTarget: 'model-config',
    elementId: 'model-selection',
  },
  {
    id: 'model.useOwnApiKey',
    labelKey: 'Use Own API Key',
    descriptionKey: 'LLM requests go directly to provider APIs',
    section: SettingsSection.MODEL_CONFIG,
    sectionLabelKey: 'Model Config',
    keywords: ['backend', 'direct', 'api', 'mode', 'toggle', 'own key'],
    navigationTarget: 'model-config',
    elementId: 'use-own-api-key',
  },
  {
    id: 'model.apiKey',
    labelKey: 'API Key Configuration',
    descriptionKey: 'Enter your LLM API key',
    section: SettingsSection.MODEL_CONFIG,
    sectionLabelKey: 'Model Config',
    keywords: ['api key', 'authentication', 'openai', 'anthropic', 'groq', 'xai', 'secret'],
    navigationTarget: 'model-config',
    elementId: 'api-key',
  },
  {
    id: 'model.serviceTier',
    labelKey: 'Service Tier',
    descriptionKey: 'Priority tier provides faster response times with higher pricing.',
    section: SettingsSection.MODEL_CONFIG,
    sectionLabelKey: 'Model Config',
    keywords: ['tier', 'priority', 'flex', 'openai', 'speed', 'pricing'],
    navigationTarget: 'model-config',
    elementId: 'service-tier',
  },

  // ── General ───────────────────────────────────────────────────────────
  {
    id: 'general.uiTheme',
    labelKey: 'UI Theme',
    descriptionKey: 'Choose the visual style for the side panel interface',
    section: SettingsSection.GENERAL,
    sectionLabelKey: 'General',
    keywords: ['theme', 'dark', 'light', 'terminal', 'chatgpt', 'appearance', 'style', 'modern'],
    navigationTarget: 'general',
    elementId: 'uiTheme',
  },
  {
    id: 'general.showTokenUsage',
    labelKey: 'Show token usage in tasks',
    descriptionKey: 'Display token consumption (input/output tokens) when tasks complete',
    section: SettingsSection.GENERAL,
    sectionLabelKey: 'General',
    keywords: ['token', 'usage', 'cost', 'consumption', 'display'],
    navigationTarget: 'general',
    elementId: 'showTokenUsage',
  },
  {
    id: 'shortcuts.keyboard',
    labelKey: 'Keyboard Shortcuts',
    descriptionKey: 'View and customize app keyboard shortcuts',
    section: SettingsSection.KEYBOARD_SHORTCUTS,
    sectionLabelKey: 'Keyboard Shortcuts',
    keywords: ['keyboard', 'shortcuts', 'hotkeys', 'keys', 'commands'],
    navigationTarget: 'keyboard-shortcuts',
    elementId: 'keyboard-shortcuts',
  },
  // ── Memory ──────────────────────────────────────────────────────────
  {
    id: 'memory.enabled',
    labelKey: 'Agent Memory',
    descriptionKey: 'Remember facts across conversations. Works with any LLM provider.',
    section: SettingsSection.MEMORY,
    sectionLabelKey: 'Memory',
    keywords: ['memory', 'remember', 'facts', 'long-term', 'preferences'],
    navigationTarget: 'memory',
    elementId: 'memoryEnabled',
    conditional: { type: 'platform', value: 'desktop' },
  },
  {
    id: 'general.language',
    labelKey: 'Language',
    descriptionKey: 'Select your preferred language for the interface',
    section: SettingsSection.GENERAL,
    sectionLabelKey: 'General',
    keywords: ['language', 'locale', 'i18n', 'translation', 'english', 'chinese'],
    navigationTarget: 'general',
    elementId: 'language',
  },
  {
    id: 'general.maxSessions',
    labelKey: 'Max Concurrent Sessions',
    descriptionKey: 'Maximum number of parallel agent sessions, including scheduled tasks',
    section: SettingsSection.GENERAL,
    sectionLabelKey: 'General',
    keywords: ['sessions', 'parallel', 'concurrent', 'limit', 'max'],
    navigationTarget: 'general',
    elementId: 'maxSessions',
  },

  // ── Storage & Cache ───────────────────────────────────────────────────
  {
    id: 'storage.cacheEnabled',
    labelKey: 'Enable Cache',
    descriptionKey: 'Enable caching to improve performance by storing frequently accessed data',
    section: SettingsSection.STORAGE,
    sectionLabelKey: 'Storage & Cache',
    keywords: ['cache', 'enable', 'toggle', 'performance'],
    navigationTarget: 'storage',
    elementId: 'cache-enabled',
  },
  {
    id: 'storage.cacheTTL',
    labelKey: 'Cache TTL (seconds)',
    descriptionKey: 'Time-to-live for cached items in seconds (default: 3600)',
    section: SettingsSection.STORAGE,
    sectionLabelKey: 'Storage & Cache',
    keywords: ['ttl', 'time', 'expiry', 'cache', 'duration', 'seconds'],
    navigationTarget: 'storage',
    elementId: 'cache-ttl',
  },
  {
    id: 'storage.cacheMaxSize',
    labelKey: 'Max Cache Size (MB)',
    descriptionKey: 'Maximum cache size in megabytes (default: 100)',
    section: SettingsSection.STORAGE,
    sectionLabelKey: 'Storage & Cache',
    keywords: ['cache', 'size', 'limit', 'megabytes', 'storage', 'quota'],
    navigationTarget: 'storage',
    elementId: 'cache-maxsize',
  },
  {
    id: 'storage.compressionEnabled',
    labelKey: 'Enable Compression',
    descriptionKey: 'Compress cached data to save storage space',
    section: SettingsSection.STORAGE,
    sectionLabelKey: 'Storage & Cache',
    keywords: ['compression', 'compress', 'zip', 'storage', 'space'],
    navigationTarget: 'storage',
    elementId: 'cache-compression-enabled',
  },
  {
    id: 'storage.persistCache',
    labelKey: 'Persist Cache to Storage',
    descriptionKey: 'Store cache data persistently across browser sessions',
    section: SettingsSection.STORAGE,
    sectionLabelKey: 'Storage & Cache',
    keywords: ['persist', 'permanent', 'save', 'browser', 'sessions'],
    navigationTarget: 'storage',
    elementId: 'cache-persist-to-storage',
  },
  {
    id: 'storage.rolloutTTL',
    labelKey: 'Rollout Expiration',
    descriptionKey: 'Set when rollout data should expire',
    section: SettingsSection.STORAGE,
    sectionLabelKey: 'Storage & Cache',
    keywords: ['rollout', 'expiration', 'expire', 'days', 'permanent'],
    navigationTarget: 'storage',
    elementId: 'rollout-ttl-unit',
  },

  // ── Tools ─────────────────────────────────────────────────────────────
  {
    id: 'tools.enableAll',
    labelKey: 'Enable All Tools',
    descriptionKey: 'Master toggle to enable or disable all browser and agent tools',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['enable', 'disable', 'all', 'master', 'toggle'],
    navigationTarget: 'tools',
    elementId: 'enable-all-tools',
  },
  {
    id: 'tools.storageTool',
    labelKey: 'Storage Tool',
    descriptionKey: 'Access browser storage (localStorage, sessionStorage, cookies)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['storage', 'localstorage', 'sessionstorage', 'cookies', 'browser'],
    navigationTarget: 'tools',
    elementId: 'storage-tool',
  },
  {
    id: 'tools.tabTool',
    labelKey: 'Tab Tool',
    descriptionKey: 'Manage browser tabs (open, close, switch, query)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['tab', 'tabs', 'browser', 'manage', 'open', 'close'],
    navigationTarget: 'tools',
    elementId: 'tab-tool',
  },
  {
    id: 'tools.webScrapingTool',
    labelKey: 'Web Scraping Tool',
    descriptionKey: 'Extract structured data from web pages',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['scraping', 'scrape', 'extract', 'web', 'data', 'crawl'],
    navigationTarget: 'tools',
    elementId: 'web-scraping-tool',
  },
  {
    id: 'tools.domTool',
    labelKey: 'DOM Tool',
    descriptionKey: 'Query and manipulate the DOM (Document Object Model)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['dom', 'document', 'html', 'query', 'selector', 'element'],
    navigationTarget: 'tools',
    elementId: 'dom-tool',
  },
  {
    id: 'tools.formAutomationTool',
    labelKey: 'Form Automation Tool',
    descriptionKey: 'Fill forms, submit data, interact with form elements',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['form', 'fill', 'submit', 'input', 'automation', 'autofill'],
    navigationTarget: 'tools',
    elementId: 'form-automation-tool',
  },
  {
    id: 'tools.navigationTool',
    labelKey: 'Navigation Tool',
    descriptionKey: 'Navigate pages, click links, handle browser navigation',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['navigate', 'navigation', 'click', 'links', 'page', 'url'],
    navigationTarget: 'tools',
    elementId: 'navigation-tool',
  },
  {
    id: 'tools.networkInterceptTool',
    labelKey: 'Network Intercept Tool',
    descriptionKey: 'Intercept and modify network requests/responses',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['network', 'intercept', 'request', 'response', 'http', 'api'],
    navigationTarget: 'tools',
    elementId: 'network-intercept-tool',
  },
  {
    id: 'tools.dataExtractionTool',
    labelKey: 'Data Extraction Tool',
    descriptionKey: 'Extract specific data patterns from pages',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['data', 'extraction', 'extract', 'pattern', 'parse'],
    navigationTarget: 'tools',
    elementId: 'data-extraction-tool',
  },
  {
    id: 'tools.pageActionTool',
    labelKey: 'Page Action Tool',
    descriptionKey: 'Perform page actions (scroll, screenshot, wait)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['page', 'action', 'scroll', 'screenshot', 'wait', 'click'],
    navigationTarget: 'tools',
    elementId: 'page-action-tool',
  },
  {
    id: 'tools.pageVisionTool',
    labelKey: 'Page Vision Tool',
    descriptionKey: 'Visual analysis of page content and layout',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['vision', 'visual', 'analysis', 'layout', 'image', 'screenshot'],
    navigationTarget: 'tools',
    elementId: 'page-vision-tool',
  },
  {
    id: 'tools.execCommand',
    labelKey: 'Execute Commands',
    descriptionKey: 'Allow agent to execute system commands (use with caution)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['command', 'execute', 'terminal', 'shell', 'system', 'run'],
    navigationTarget: 'tools',
    elementId: 'exec-command',
  },
  {
    id: 'tools.webSearch',
    labelKey: 'Web Search',
    descriptionKey: 'Enable web search capabilities for the agent',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['search', 'web', 'google', 'bing', 'internet', 'query'],
    navigationTarget: 'tools',
    elementId: 'web-search',
  },
  {
    id: 'tools.fileOperations',
    labelKey: 'File Operations (Not Available)',
    descriptionKey: 'Allow agent to read, write, and manage files (Coming in future update)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['file', 'read', 'write', 'manage', 'filesystem'],
    navigationTarget: 'tools',
    elementId: 'file-operations',
    conditional: { type: 'feature', value: 'disabled' },
  },
  {
    id: 'tools.mcpTools',
    labelKey: 'MCP Tools',
    descriptionKey: 'Enable Model Context Protocol tools from connected MCP servers',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['mcp', 'protocol', 'tools', 'external', 'server'],
    navigationTarget: 'tools',
    elementId: 'mcp-tools',
  },
  {
    id: 'tools.timeout',
    labelKey: 'Tool Timeout (ms)',
    descriptionKey: 'Maximum time (in milliseconds) a tool can run before timeout (default: 30000)',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['timeout', 'time', 'limit', 'milliseconds', 'duration'],
    navigationTarget: 'tools',
    elementId: 'tool-timeout',
  },
  {
    id: 'tools.sandboxPolicy',
    labelKey: 'Sandbox Policy',
    descriptionKey: 'Security level for tool execution environment',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['sandbox', 'security', 'policy', 'safe', 'execution'],
    navigationTarget: 'tools',
    elementId: 'sandbox-mode',
  },
  {
    id: 'tools.executionMode',
    labelKey: 'Execution Mode',
    descriptionKey:
      'All commands run inside an OS-native sandbox. Writes restricted to workspace directory.',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['execution', 'mode', 'safe', 'power', 'auto', 'sandbox', 'terminal'],
    navigationTarget: 'tools',
    elementId: 'execution-mode',
    conditional: { type: 'platform', value: 'desktop' },
  },
  {
    id: 'tools.workspaceAccess',
    labelKey: 'Workspace Access',
    descriptionKey: 'How the workspace directory is mounted in the sandbox',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['workspace', 'access', 'mount', 'directory', 'read', 'write'],
    navigationTarget: 'tools',
    elementId: 'workspace-access',
    conditional: { type: 'platform', value: 'desktop' },
  },
  {
    id: 'tools.networkMode',
    labelKey: 'Network Access',
    descriptionKey: 'Whether sandboxed commands can access the network',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['network', 'access', 'internet', 'sandbox', 'restricted'],
    navigationTarget: 'tools',
    elementId: 'network-mode',
    conditional: { type: 'platform', value: 'desktop' },
  },
  {
    id: 'tools.bindMounts',
    labelKey: 'Additional Bind Mounts',
    descriptionKey: 'Extra directories accessible inside the sandbox',
    section: SettingsSection.TOOLS,
    sectionLabelKey: 'Tools',
    keywords: ['bind', 'mount', 'directory', 'path', 'sandbox', 'volume'],
    navigationTarget: 'tools',
    elementId: 'bind-mounts',
    conditional: { type: 'platform', value: 'desktop' },
  },

  // ── MCP Servers ───────────────────────────────────────────────────────
  {
    id: 'mcp.servers',
    labelKey: 'Configured Servers',
    descriptionKey:
      'Connect to Model Context Protocol (MCP) servers to extend the agent with external tools.',
    section: SettingsSection.MCP_SERVERS,
    sectionLabelKey: 'MCP Servers',
    keywords: ['mcp', 'server', 'connect', 'external', 'protocol', 'configure'],
    navigationTarget: 'mcp-servers',
    elementId: 'mcp-configured-servers',
  },
  {
    id: 'mcp.tools',
    labelKey: 'Available Tools',
    descriptionKey: 'Tools provided by connected MCP servers',
    section: SettingsSection.MCP_SERVERS,
    sectionLabelKey: 'MCP Servers',
    keywords: ['mcp', 'tools', 'available', 'external', 'server'],
    navigationTarget: 'mcp-servers',
    elementId: 'mcp-available-tools',
  },
  {
    id: 'mcp.debugLogging',
    labelKey: 'Enable debug logging',
    descriptionKey: 'Log MCP protocol messages to browser console for debugging',
    section: SettingsSection.MCP_SERVERS,
    sectionLabelKey: 'MCP Servers',
    keywords: ['debug', 'logging', 'console', 'mcp', 'protocol', 'troubleshoot'],
    navigationTarget: 'mcp-servers',
    elementId: 'mcp-debug-logging',
  },

  // ── Approval & Safety ───────────────────────────────────────────────
  {
    id: 'approval.mode',
    labelKey: 'Approval Mode',
    descriptionKey: 'Controls how aggressively the agent asks for approval.',
    section: SettingsSection.APPROVAL,
    sectionLabelKey: 'Approval & Safety',
    keywords: ['approval', 'mode', 'balanced', 'yolo', 'auto-approve', 'risk', 'safety'],
    navigationTarget: 'approval',
    elementId: 'approval-mode',
  },
  {
    id: 'approval.trustedDomains',
    labelKey: 'Trusted Domains',
    descriptionKey: 'All actions are auto-approved on these domains.',
    section: SettingsSection.APPROVAL,
    sectionLabelKey: 'Approval & Safety',
    keywords: ['trusted', 'domains', 'whitelist', 'auto-approve', 'safe', 'allow'],
    navigationTarget: 'approval',
    elementId: 'trusted-domains',
  },
  {
    id: 'approval.blockedDomains',
    labelKey: 'Blocked Domains',
    descriptionKey: 'All actions are denied on these domains.',
    section: SettingsSection.APPROVAL,
    sectionLabelKey: 'Approval & Safety',
    keywords: ['blocked', 'domains', 'blacklist', 'deny', 'block', 'restrict'],
    navigationTarget: 'approval',
    elementId: 'blocked-domains',
  },

  // ── Extension & Permission ────────────────────────────────────────────
  {
    id: 'extension.enabled',
    labelKey: 'Enable Extension',
    descriptionKey: 'Master toggle to enable or disable the extension',
    section: SettingsSection.EXTENSION,
    sectionLabelKey: 'Extension & Permission',
    keywords: ['extension', 'enable', 'disable', 'master', 'toggle'],
    navigationTarget: 'extension',
    elementId: 'extension-enabled',
  },
  {
    id: 'extension.contentScripts',
    labelKey: 'Enable Content Scripts',
    descriptionKey: 'Allow content scripts to run on web pages',
    section: SettingsSection.EXTENSION,
    sectionLabelKey: 'Extension & Permission',
    keywords: ['content', 'scripts', 'inject', 'web', 'pages', 'permission'],
    navigationTarget: 'extension',
    elementId: 'content-script-enabled',
  },
  {
    id: 'extension.updateChannel',
    labelKey: 'Update Channel',
    descriptionKey: 'Choose which update channel to follow',
    section: SettingsSection.EXTENSION,
    sectionLabelKey: 'Extension & Permission',
    keywords: ['update', 'channel', 'stable', 'beta', 'version'],
    navigationTarget: 'extension',
    elementId: 'update-channel',
  },
  {
    id: 'extension.storageQuota',
    labelKey: 'Storage Quota Warning (%)',
    descriptionKey: 'Show warning when storage usage exceeds this percentage (default: 90%)',
    section: SettingsSection.EXTENSION,
    sectionLabelKey: 'Extension & Permission',
    keywords: ['storage', 'quota', 'warning', 'percentage', 'limit', 'disk'],
    navigationTarget: 'extension',
    elementId: 'storage-quota',
  },
  {
    id: 'extension.allowedOrigins',
    labelKey: 'Allowed Origins',
    descriptionKey: 'List of allowed origins (one per line). Supports wildcards (*).',
    section: SettingsSection.EXTENSION,
    sectionLabelKey: 'Extension & Permission',
    keywords: ['origins', 'cors', 'whitelist', 'domain', 'url', 'allowed', 'permission'],
    navigationTarget: 'extension',
    elementId: 'allowed-origins',
  },
];
