/**
 * Message type constants for inter-component communication.
 *
 * Used by the compatibility shim in webfront/lib/messaging.ts to map
 * legacy MessageType values to service paths during the message_routing_v2
 * migration. Will be removed once all call sites use serviceRequest() directly.
 *
 * @module core/message-types
 */

export enum MessageType {
  // Core protocol messages
  SUBMISSION = 'SUBMISSION',
  EVENT = 'EVENT',

  // Connection management
  PING = 'PING',
  PONG = 'PONG',
  HEALTH_CHECK = 'HEALTH_CHECK',
  HEALTH_STATUS = 'HEALTH_STATUS',

  // State queries
  GET_STATE = 'GET_STATE',
  STATE_UPDATE = 'STATE_UPDATE',

  // Tab operations
  TAB_COMMAND = 'TAB_COMMAND',

  // Storage operations
  STORAGE_GET = 'STORAGE_GET',
  STORAGE_SET = 'STORAGE_SET',

  // Tool execution messages
  TOOL_EXECUTE = 'TOOL_EXECUTE',

  // Approval messages
  APPROVAL_REQUEST = 'APPROVAL_REQUEST',

  // Diff tracking messages
  DIFF_GENERATED = 'DIFF_GENERATED',

  // Session management
  SESSION_RESET = 'SESSION_RESET',
  SESSION_RESET_COMPLETE = 'SESSION_RESET_COMPLETE',
  RESUME_SESSION = 'RESUME_SESSION',
  RESUME_SESSION_COMPLETE = 'RESUME_SESSION_COMPLETE',

  // ResponseEvent streaming messages (legacy — kept for TauriMessageService compat)
  RESPONSE_EVENT = 'RESPONSE_EVENT',
  RESPONSE_OUTPUT_TEXT_DELTA = 'RESPONSE_OUTPUT_TEXT_DELTA',
  RESPONSE_REASONING_CONTENT_DELTA = 'RESPONSE_REASONING_CONTENT_DELTA',

  // Agent control
  INTERRUPT = 'STOP_AGENT_SESSION',

  // Configuration management
  CONFIG_UPDATE = 'CONFIG_UPDATE',
  AGENT_REINITIALIZED = 'AGENT_REINITIALIZED',

  // Authentication management
  INIT_AUTH = 'INIT_AUTH',

  // MCP Server Integration messages
  MCP_GET_SERVERS = 'MCP_GET_SERVERS',
  MCP_ADD_SERVER = 'MCP_ADD_SERVER',
  MCP_UPDATE_SERVER = 'MCP_UPDATE_SERVER',
  MCP_REMOVE_SERVER = 'MCP_REMOVE_SERVER',
  MCP_CONNECT = 'MCP_CONNECT',
  MCP_DISCONNECT = 'MCP_DISCONNECT',
  MCP_GET_CONNECTION = 'MCP_GET_CONNECTION',
  MCP_GET_CONNECTIONS = 'MCP_GET_CONNECTIONS',
  MCP_GET_ALL_TOOLS = 'MCP_GET_ALL_TOOLS',
  MCP_EXECUTE_TOOL = 'MCP_EXECUTE_TOOL',
  MCP_GET_ALL_RESOURCES = 'MCP_GET_ALL_RESOURCES',
  MCP_READ_RESOURCE = 'MCP_READ_RESOURCE',

  // Task Scheduler messages
  SCHEDULER_CREATE_DRAFT_TASK = 'SCHEDULER_CREATE_DRAFT_TASK',
  SCHEDULER_SCHEDULE_TASK = 'SCHEDULER_SCHEDULE_TASK',
  SCHEDULER_TRIGGER_TASK = 'SCHEDULER_TRIGGER_TASK',
  SCHEDULER_CANCEL_TASK = 'SCHEDULER_CANCEL_TASK',
  SCHEDULER_COMPLETE_TASK = 'SCHEDULER_COMPLETE_TASK',
  SCHEDULER_FAIL_TASK = 'SCHEDULER_FAIL_TASK',
  SCHEDULER_PAUSE_QUEUE = 'SCHEDULER_PAUSE_QUEUE',
  SCHEDULER_RESUME_QUEUE = 'SCHEDULER_RESUME_QUEUE',
  SCHEDULER_GET_DRAFT_TASKS = 'SCHEDULER_GET_DRAFT_TASKS',
  SCHEDULER_GET_SCHEDULED_TASKS = 'SCHEDULER_GET_SCHEDULED_TASKS',
  SCHEDULER_GET_MISSED_TASKS = 'SCHEDULER_GET_MISSED_TASKS',
  SCHEDULER_GET_QUEUE = 'SCHEDULER_GET_QUEUE',
  SCHEDULER_GET_ARCHIVED_TASKS = 'SCHEDULER_GET_ARCHIVED_TASKS',
  SCHEDULER_GET_STATE = 'SCHEDULER_GET_STATE',
  SCHEDULER_GET_TASK_DETAILS = 'SCHEDULER_GET_TASK_DETAILS',
  SCHEDULER_TASK_STATUS_CHANGED = 'SCHEDULER_TASK_STATUS_CHANGED',
  SCHEDULER_STATE_CHANGED = 'SCHEDULER_STATE_CHANGED',
  SCHEDULER_EVENT = 'SCHEDULER_EVENT',

  // Session management messages (Feature 015)
  SESSION_LIST = 'SESSION_LIST',
  SESSION_GET_ACTIVE_COUNT = 'SESSION_GET_ACTIVE_COUNT',
  SESSION_EVENT = 'SESSION_EVENT',
  SET_MAX_CONCURRENT_SESSIONS = 'SET_MAX_CONCURRENT_SESSIONS',

  // A2A Agent-to-Agent Protocol messages
  A2A_GET_AGENTS = 'A2A_GET_AGENTS',
  A2A_ADD_AGENT = 'A2A_ADD_AGENT',
  A2A_UPDATE_AGENT = 'A2A_UPDATE_AGENT',
  A2A_REMOVE_AGENT = 'A2A_REMOVE_AGENT',
  A2A_CONNECT = 'A2A_CONNECT',
  A2A_DISCONNECT = 'A2A_DISCONNECT',
  A2A_GET_CONNECTION = 'A2A_GET_CONNECTION',
  A2A_GET_CONNECTIONS = 'A2A_GET_CONNECTIONS',
  A2A_GET_ALL_SKILLS = 'A2A_GET_ALL_SKILLS',
  A2A_EXECUTE_SKILL = 'A2A_EXECUTE_SKILL',
  A2A_CANCEL_TASK = 'A2A_CANCEL_TASK',

  // Vault operations
  VAULT_STATUS = 'vault:status',
  VAULT_UNLOCK = 'vault:unlock',
  VAULT_LOCK = 'vault:lock',

  // PIN operations
  PIN_SET = 'vault:pin:set',
  PIN_CHANGE = 'vault:pin:change',
  PIN_REMOVE = 'vault:pin:remove',
  PIN_FORGOT = 'vault:pin:forgot',

  // Agent Skills messages
  SKILLS_LIST = 'SKILLS_LIST',
  SKILLS_LOAD = 'SKILLS_LOAD',
  SKILLS_SAVE = 'SKILLS_SAVE',
  SKILLS_DELETE = 'SKILLS_DELETE',
  SKILLS_UPDATE_MODE = 'SKILLS_UPDATE_MODE',
  SKILLS_IMPORT = 'SKILLS_IMPORT',
  SKILLS_EXPORT = 'SKILLS_EXPORT',
  SKILLS_TRUST = 'SKILLS_TRUST',
}
