import type { ShortcutAction, ShortcutActionMeta, ShortcutContext } from './types';

export const SHORTCUT_CONTEXTS = [
  'Global',
  'Chat',
  'SlashCommand',
  'Modal',
  'SettingsSearch',
  'SettingsModelSelector',
  'ModelPicker',
  'SchedulerModal',
  'Skills',
  'DesktopGlobal',
  'ExtensionCommand',
] as const satisfies readonly ShortcutContext[];

export const SHORTCUT_ACTIONS = [
  'app:zoomIn',
  'app:zoomOut',
  'app:zoomReset',
  'app:toggleWindow',
  'app:focusInput',
  'app:quickAction',
  'chat:submit',
  'chat:newline',
  'slash:next',
  'slash:previous',
  'slash:accept',
  'slash:dismiss',
  'modal:dismiss',
  'modelPicker:dismiss',
  'scheduler:dismiss',
  'skills:dismiss',
  'settingsSearch:next',
  'settingsSearch:previous',
  'settingsSearch:accept',
  'settingsSearch:dismiss',
  'settingsModelSelector:next',
  'settingsModelSelector:previous',
  'settingsModelSelector:accept',
  'settingsModelSelector:dismiss',
  'settingsModelSelector:first',
  'settingsModelSelector:last',
] as const satisfies readonly ShortcutAction[];

export const CONTEXT_PRIORITY: Record<ShortcutContext, number> = {
  SlashCommand: 100,
  Modal: 90,
  SchedulerModal: 90,
  ModelPicker: 80,
  Skills: 80,
  SettingsSearch: 70,
  SettingsModelSelector: 70,
  Chat: 50,
  Global: 0,
  DesktopGlobal: 0,
  ExtensionCommand: 0,
};

export const SHORTCUT_ACTION_META: Record<ShortcutAction, ShortcutActionMeta> = {
  'app:zoomIn': {
    action: 'app:zoomIn',
    defaultContext: 'Global',
    scopes: ['inApp'],
    label: 'Zoom in',
    description: 'Increase the Browserx UI zoom level.',
    owner: 'webfront',
    configurable: true,
  },
  'app:zoomOut': {
    action: 'app:zoomOut',
    defaultContext: 'Global',
    scopes: ['inApp'],
    label: 'Zoom out',
    description: 'Decrease the Browserx UI zoom level.',
    owner: 'webfront',
    configurable: true,
  },
  'app:zoomReset': {
    action: 'app:zoomReset',
    defaultContext: 'Global',
    scopes: ['inApp'],
    label: 'Reset zoom',
    description: 'Reset Browserx UI zoom to 100%.',
    owner: 'webfront',
    configurable: true,
  },
  'app:toggleWindow': {
    action: 'app:toggleWindow',
    defaultContext: 'DesktopGlobal',
    scopes: ['desktopGlobal', 'extensionCommand'],
    label: 'Toggle window',
    description: 'Show Browserx from the desktop app or browser extension.',
    owner: 'desktop',
    configurable: false,
  },
  'app:focusInput': {
    action: 'app:focusInput',
    defaultContext: 'DesktopGlobal',
    scopes: ['desktopGlobal'],
    label: 'Focus input',
    description: 'Show the desktop window and focus the message input.',
    owner: 'desktop',
    configurable: false,
  },
  'app:quickAction': {
    action: 'app:quickAction',
    defaultContext: 'DesktopGlobal',
    scopes: ['desktopGlobal', 'extensionCommand'],
    label: 'Quick action',
    description: 'Open the quick action flow for the current page.',
    owner: 'extension',
    configurable: false,
  },
  'chat:submit': {
    action: 'chat:submit',
    defaultContext: 'Chat',
    scopes: ['inApp'],
    label: 'Submit message',
    description: 'Send the current message.',
    owner: 'webfront',
    configurable: true,
  },
  'chat:newline': {
    action: 'chat:newline',
    defaultContext: 'Chat',
    scopes: ['inApp'],
    label: 'Insert newline',
    description: 'Insert a new line in the message input.',
    owner: 'webfront',
    configurable: true,
  },
  'slash:next': {
    action: 'slash:next',
    defaultContext: 'SlashCommand',
    scopes: ['inApp'],
    label: 'Next command',
    description: 'Move to the next slash command.',
    owner: 'webfront',
    configurable: true,
  },
  'slash:previous': {
    action: 'slash:previous',
    defaultContext: 'SlashCommand',
    scopes: ['inApp'],
    label: 'Previous command',
    description: 'Move to the previous slash command.',
    owner: 'webfront',
    configurable: true,
  },
  'slash:accept': {
    action: 'slash:accept',
    defaultContext: 'SlashCommand',
    scopes: ['inApp'],
    label: 'Run command',
    description: 'Run the selected slash command.',
    owner: 'webfront',
    configurable: true,
  },
  'slash:dismiss': {
    action: 'slash:dismiss',
    defaultContext: 'SlashCommand',
    scopes: ['inApp'],
    label: 'Dismiss commands',
    description: 'Close the slash command menu.',
    owner: 'webfront',
    configurable: true,
  },
  'modal:dismiss': {
    action: 'modal:dismiss',
    defaultContext: 'Modal',
    scopes: ['inApp'],
    label: 'Close modal',
    description: 'Close the active modal.',
    owner: 'webfront',
    configurable: true,
  },
  'modelPicker:dismiss': {
    action: 'modelPicker:dismiss',
    defaultContext: 'ModelPicker',
    scopes: ['inApp'],
    label: 'Close model picker',
    description: 'Close the model picker.',
    owner: 'webfront',
    configurable: true,
  },
  'scheduler:dismiss': {
    action: 'scheduler:dismiss',
    defaultContext: 'SchedulerModal',
    scopes: ['inApp'],
    label: 'Close scheduler dialog',
    description: 'Close the active scheduler dialog.',
    owner: 'scheduler',
    configurable: true,
  },
  'skills:dismiss': {
    action: 'skills:dismiss',
    defaultContext: 'Skills',
    scopes: ['inApp'],
    label: 'Close skills',
    description: 'Close the skills page overlay.',
    owner: 'webfront',
    configurable: true,
  },
  'settingsSearch:next': {
    action: 'settingsSearch:next',
    defaultContext: 'SettingsSearch',
    scopes: ['inApp'],
    label: 'Next search result',
    description: 'Move to the next settings search result.',
    owner: 'settings',
    configurable: true,
  },
  'settingsSearch:previous': {
    action: 'settingsSearch:previous',
    defaultContext: 'SettingsSearch',
    scopes: ['inApp'],
    label: 'Previous search result',
    description: 'Move to the previous settings search result.',
    owner: 'settings',
    configurable: true,
  },
  'settingsSearch:accept': {
    action: 'settingsSearch:accept',
    defaultContext: 'SettingsSearch',
    scopes: ['inApp'],
    label: 'Open search result',
    description: 'Open the selected settings search result.',
    owner: 'settings',
    configurable: true,
  },
  'settingsSearch:dismiss': {
    action: 'settingsSearch:dismiss',
    defaultContext: 'SettingsSearch',
    scopes: ['inApp'],
    label: 'Clear settings search',
    description: 'Clear settings search.',
    owner: 'settings',
    configurable: true,
  },
  'settingsModelSelector:next': {
    action: 'settingsModelSelector:next',
    defaultContext: 'SettingsModelSelector',
    scopes: ['inApp'],
    label: 'Next model',
    description: 'Move to the next settings model option.',
    owner: 'settings',
    configurable: true,
  },
  'settingsModelSelector:previous': {
    action: 'settingsModelSelector:previous',
    defaultContext: 'SettingsModelSelector',
    scopes: ['inApp'],
    label: 'Previous model',
    description: 'Move to the previous settings model option.',
    owner: 'settings',
    configurable: true,
  },
  'settingsModelSelector:accept': {
    action: 'settingsModelSelector:accept',
    defaultContext: 'SettingsModelSelector',
    scopes: ['inApp'],
    label: 'Select model',
    description: 'Select the focused model option.',
    owner: 'settings',
    configurable: true,
  },
  'settingsModelSelector:dismiss': {
    action: 'settingsModelSelector:dismiss',
    defaultContext: 'SettingsModelSelector',
    scopes: ['inApp'],
    label: 'Close model selector',
    description: 'Close the settings model selector.',
    owner: 'settings',
    configurable: true,
  },
  'settingsModelSelector:first': {
    action: 'settingsModelSelector:first',
    defaultContext: 'SettingsModelSelector',
    scopes: ['inApp'],
    label: 'First model',
    description: 'Move to the first settings model option.',
    owner: 'settings',
    configurable: true,
  },
  'settingsModelSelector:last': {
    action: 'settingsModelSelector:last',
    defaultContext: 'SettingsModelSelector',
    scopes: ['inApp'],
    label: 'Last model',
    description: 'Move to the last settings model option.',
    owner: 'settings',
    configurable: true,
  },
};

export function isShortcutContext(value: string): value is ShortcutContext {
  return (SHORTCUT_CONTEXTS as readonly string[]).includes(value);
}

export function isShortcutAction(value: string): value is ShortcutAction {
  return (SHORTCUT_ACTIONS as readonly string[]).includes(value);
}
